name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build-and-test:
        name: Build, checkstyle and test
        runs-on: ubuntu-latest
        steps:
        - name: Check out the repository
          uses: actions/checkout@v4
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: '1.23'
        - name: Install Dependencies
          run: make get-dependencies
        - name: Format Code
          run: make reformat
        - name: Check Code
          run: make check-typing
        - name: Run Unit Tests
          run: make test-unit
        - name: Run Load Tests
          run: make test-load
        - name: Build Project
          run: make build
        - name: Clean up
          run: make clean